nome = input('como voce se chama?')
idade = input('qual é a sua idade?')
peso = input('Qual é o seu peso?')
print (nome, idade, peso)
print ('Legal! Seu nome é',nome,',voce tem',idade,'anos e pesa ',peso,' quilos!')
